spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Oik+NaG6qKel3a1eu0wy6bnMb3iUnlzw0uVNkwnZS00vSNjsO1JMy0Z+yAtzoX9ZYQRmro+mVXWMDalRN5qhOg==
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
  data:
    solr:
      host: http://106.14.57.231:8088/solr/

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJiik2QCFLJFwUtEzfYdii8jjCnzX+mExp2GHspQfi0GnwXX9VMd4yFUejDs0XY+tR10+Vk+zQD5cpTZGa8d1KECAwEAAQ==


dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 106.14.57.231:2181
  protocol:
    port: 28811
server:
  port: 8081



